---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: redis-sc
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
parameters:
  type: gp2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    type: redis-pv-type
spec:
  storageClassName: redis-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0bfe566d3f8499275
    fsType: ext4
---
# if using kops, automatically provision EBS storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
spec:
  storageClassName: redis-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
