apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: redis-cs
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
          name: redis-client
        resources:
          limits:
            cpu: "0.5"
            memory: 1.0Gi
          requests:
            cpu: "0.3"
            memory: 0.3Gi
        volumeMounts:
        - mountPath: /data
          name: redis-persistent-storage
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: redis-persistent-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
