apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis
    name: redis-svc
spec:
  type: NodePort
  ports:
  - port: 6379
    nodePort: 32079
    name: redis-client
    protocol: TCP
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cs
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis-client
  selector:
    app: redis
---
