apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: query
    port: 6125
  - name: ui
    port: 8081
  selector:
    app: flink
    component: jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: flink-cs
  labels:
    app: flink
    name: flink-cs
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 32081
    name: ui
    protocol: TCP
  - port: 6123
    nodePort: 32023
    name: rpc
    protocol: TCP
  selector:
    app: flink
    component: jobmanager
---
